### ISSUE TITLE
Nice

### ISSUE THREAD

**Issue by sabbathin** [CalebEverett/futures-app#1]
Pretty cool job, unfortunately there are still some modules missing in the js version. As a matter of fact, there's a subtle error in the readme, wich leads you to clone python api version. I dont handle python, tried to run it but failed, but I can't wait for JS, in wich I'd be more helpful once it's done, we could wrap it around GPU kernel. Good luck.

**Comment by CalebEverett** [comment]
The application requires the python api server to be running. If you clone the python api repo and start the server per the instructions there, and then clone and start the React app in this repo, it should work.

**Comment by sabbathin** [comment]
Thank you for you answer, well, my mistake. Did not see that comming, however, this is is all I get with my "pythonesse super powers", followed instructions, even used the pre-commits wich I did not see the first 3 times i read the readme. Not your fault of course silly long COVID playing on me. I better stay off and wait until the green bar is fuul, good luck.
+←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     Started reloader process [←[36m←[1m276←[0m] using ←[36m←[1mstatreload←[0m
Process SpawnProcess-1:
Traceback (most recent call last):
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 50, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\server.py", line 57, in serve
    config.load()
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\config.py", line 318, in load
    self.loaded_app = import_from_string(self.app)
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\importer.py", line 25, in import_from_string
    raise exc from None
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\uvicorn\importer.py", line 22, in import_from_string
    module = importlib.import_module(module_str)
  File "c:\users\qaval\appdata\local\programs\python\python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Users\qaval\.virtualenvs\futures-api-V9lV2C1M\.\api\__init__.py", line 5, in <module>
    from binance import AsyncClient
ImportError: cannot import name 'AsyncClient' from 'binance' (c:\users\qaval\appdata\local\programs\python\python39\lib\site-packages\binance\__init__.py)
